### ISSUE TITLE
Statistics Dashboard

### ISSUE THREAD

**Issue by JackBlake-zkq** [DSSD-Madison/Red-CORAL#7]
## The verbatim ask from Red CORAL:

> Number of incidents per year, per municipality, per department for all categories of incidents, types of events etc...
> 
> Indicators, graphs, labels, bar graphs, cakes, etc. Data set: users should be able to search by names, armed groups etc... to be defined later
> 
> Possibility of adding filters. For example, what is the percentage of this type of incidents in this region during the year 2023, etc... to be defined later

### Create a page where:

User selects filters
- [x] all the same filters as the map
  - [x] country, department, municipality #74 
  - [x] category, type of event #71 
  - [x] year range #70 
- [x] default to no filters i.e. everything selected

Display:
- [x] Number of Incidents selected #81 
- [x] Percentage of Total Number of Incidents #79 
- [x] Line Graph of Number of Incidents (meeting selected filters) for each year in the selected year range #80

**Comment by JackBlake-zkq** [comment]
Dropping this for now, not a priority

**Comment by JackBlake-zkq** [comment]
Nevermind, this is back on the table

**Comment by JackBlake-zkq** [comment]
Removed from scope for this semester, leaving up since we'll still want it in the future
